apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www
spec:
  secretName: www-tls
  privateKey:
    rotationPolicy: Always
  commonName: test.az.dev24.se
  dnsNames:
    - test.az.dev24.se
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - name: nginx1
        image: nginx:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 443
        volumeMounts:
        - name: www-tls
          mountPath: "/etc/nginx/tls"
        - name: nginx-config
          mountPath: "/etc/nginx/conf.d/default.conf"
          subPath: default.conf

      volumes:
      - name: www-tls
        secret:
          secretName: www-tls
      - name: nginx-config
        configMap:
          name: nginx-config


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 443 ssl;
      server_name test.az.dev24.se;

      ssl_certificate /etc/nginx/tls/tls.crt;
      ssl_certificate_key /etc/nginx/tls/tls.key;

      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }


