apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
      type: frontend
  template:
    metadata:
      labels:
        app: nginx1
        type: frontend
    spec:
      containers:
      - name: nginx1
        image: nginx:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: nginx1-html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx1-service
spec:
  selector:
    app: nginx1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx1-html
data:
  index.html: |
    <html>
    <head>
      <title>{{NAME}} 1</title>
    </head>
    <body>
      <h1>Welcome to {{NAME}} 1</h1>
    </body>
    </html>