apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-invalid-owner
  annotations:
    owner: "johndoe@someone.com"
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "64Mi"
        cpu: "500m"
    ports:
    - containerPort: 80