apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-resources
  annotations:
    owner: "johndoe@mycompany.tld"
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
    ports:
    - containerPort: 80