apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-no-resources
  annotations:
    owner: "johndoe@mycompany.tld"
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80